### ISSUE TITLE
Editing a project title completely hoses the undo manager and document dirty state

### ISSUE THREAD

**Issue by joxl** [editxt/editxt#11]
### To reproduce:
- Launch EditXT
- Edit a project title (e.g. double-click the title)
- Press `[Enter]` or `[Esc]` (to either save or discard the title change)
- Click on an open document and change it in some way

**OBSERVE:** The modified document's *dirty* indicator (doc. close button`(x)`) does not show the document is dirty.

**EXPECTED:** The modified document's close button turns red to indicate the document is dirty.

(cont...)
- Open a new document (`[Cmd]+n`)
- Enter some text (e.g. `Hello world`)
- Save the document somewhere with a unique name (e.g. `file1.txt`)
- Open another new document (`[Cmd]+n`)
- Enter some text (e.g. `foo bar`)
- Save the document somewhere with a unique name (e.g. `file2.txt`)
- Perform a single *undo* operation (`[Cmd]+z`)
- *Observe:* the text `foo bar` vanishes from `file2.txt` (this is expected)
- Perform another single *undo* operation (`[Cmd]+z`)

**OBSERVE:** Nothing visually or audibly happens in `file2.txt`.  Clicking back over to `file1.txt`, the document is empty.

**EXPECTED:** Hear the audible *"cannot perform operation"* sound, `file1.txt` should **not** be modified by an *undo* action performed while `file2.txt` is the active document.

----
### Other negative side effects of this bug:
- Whenever a project title is modified, the entire previous undo history (for all documents) is lost.

**Comment by millerdev** [comment]
Fixed by 0f1bb70c5f575d7d18b3123d56dbc71a096aa171
