### ISSUE TITLE
Copied text is put on the clipboard as Rich Text

### ISSUE THREAD

**Issue by joxl** [editxt/editxt#14]
Copying text from EditXT to be pasted into other applications results in the EditXT font settings being preserved (Rich Text) on the clipboard along with the copied data.

## Steps to reproduce
1. Open new document (⌘N) and type some text.
1. Select typed text (⌘A) and copy (⌘C)
![image](https://user-images.githubusercontent.com/1731363/77363258-cc2f6900-6d28-11ea-9c45-715959b977ed.png)

1. Launch another application which supports Rich Text (e.g. TextEdit.app)
1. Choose font settings other than those in EditXT and type some comparison text.
![image](https://user-images.githubusercontent.com/1731363/77363504-38aa6800-6d29-11ea-83ba-150db9cfb964.png)

1. Paste the text copied from EditXT (⌘V)

**Observe:** pasted text is formatted with font settings from EditXT:
![image](https://user-images.githubusercontent.com/1731363/77363623-727b6e80-6d29-11ea-816f-b37c76d6b4ff.png)

**Expected:** pasted text be formatted with font settings from current application.

**Comment by millerdev** [comment]
This is a feature, not a bug. The _Paste and Match Style_ option in the _Edit_ menu of TextEdit should do what you want..
